name: CI (Python 3.12 + uv)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: |
          if [ -f "uv.lock" ]; then
            uv sync --dev
          elif [ -f "pyproject.toml" ]; then
            uv pip install -e .
            uv pip install pytest
          elif [ -f "requirements.txt" ]; then
            uv pip install -r requirements.txt
            uv pip install pytest
          fi

      - name: Run tests
        run: |
          if [ -f "run_pytest.sh" ]; then
            sh ./run_pytest.sh
          else
            uv run pytest -q
          fi